from ubuntu:16.04
RUN apt-get update -y \
    && apt-get install git \
    && git clone --depth 1 https://github.com/pyenv/pyenv.git ~/.pyenv \
    && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc \
    && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc \
    && echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc \
    && source ~/.bashrc \
    && pyenv install 3.9.6 \
    && pyenv global 3.9.6 \
    && pip3 install --upgrade pip \
    && pip3 install 'buildbot[bundle]'
    
